title: Jason-zheng
description: 这是一个最初
template:
  repo: jason-zheng-template
  name: jason-zheng
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
